<?php
use Illuminate\Database\Seeder;

class BuildingsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('buildings')->truncate();
  
        DB::table('buildings')->insert([
            [
                'project_name' => 'ビル#1',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:01:00',
                'updated_at' => '2015-08-16 00:01:00',
            ],
            [
                'project_name' => 'ビル#2',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:02:00',
                'updated_at' => '2015-08-16 00:02:00',
            ],
            [
                'project_name' => 'ビル#3',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',             
                'created_at' => '2015-08-16 00:03:00',
                'updated_at' => '2015-08-16 00:03:00',
            ],
            [
                'project_name' => 'ビル#4',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',                 
                'created_at' => '2015-08-16 00:04:00',
                'updated_at' => '2015-08-16 00:04:00',
            ],
            [
                'project_name' => 'ビル#5',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',              
                'created_at' => '2015-08-16 00:05:00',
                'updated_at' => '2015-08-16 00:05:00',
            ],
            [
                'project_name' => 'ビル#6',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',                 
                'created_at' => '2015-08-16 00:06:00',
                'updated_at' => '2015-08-16 00:06:00',
            ],
            [
                'project_name' => 'ビル#7',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',              
                'created_at' => '2015-08-16 00:07:00',
                'updated_at' => '2015-08-16 00:07:00',
            ],
            [
                'project_name' => 'ビル#8',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',              
                'created_at' => '2015-08-16 00:08:00',
                'updated_at' => '2015-08-16 00:08:00',
            ],
            [
                'project_name' => 'ビル#9',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',                 
                'created_at' => '2015-08-16 00:09:00',
                'updated_at' => '2015-08-16 00:09:00',
            ],
            [
                'project_name' => 'ビル#10',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',             
                'created_at' => '2015-08-16 00:10:00',
                'updated_at' => '2015-08-16 00:10:00',
            ],
            [
                'project_name' => 'ビル#11',
                'user_name' => '担当一郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'b_data4' => 'data4',
                'b_data5' => 'data5',
                'b_data6' => 'data6',
                'b_data7' => 'data7',
                'b_data8' => 'data8',
                'b_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',             
                'created_at' => '2015-08-16 00:11:00',
                'updated_at' => '2015-08-16 00:11:00',
            ],
        ]);
    }
}
