<?php
use Illuminate\Database\Seeder;

class MansionsTableSeeder extends Seeder
{
   /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('mansions')->truncate();
  
        DB::table('mansions')->insert([
            [
                'project_name' => 'マンション#1',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:01:00',
                'updated_at' => '2015-08-16 00:01:00',
            ],
            [
                'project_name' => 'マンション#2',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:02:00',
                'updated_at' => '2015-08-16 00:02:00',
            ],
            [
                'project_name' => 'マンション#3',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:03:00',
                'updated_at' => '2015-08-16 00:03:00',
            ],
            [
                'project_name' => 'マンション#4',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:04:00',
                'updated_at' => '2015-08-16 00:04:00',
            ],
            [
                'project_name' => 'マンション#5',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:05:00',
                'updated_at' => '2015-08-16 00:05:00',
            ],
            [
                'project_name' => 'マンション#6',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',             
                'created_at' => '2015-08-16 00:06:00',
                'updated_at' => '2015-08-16 00:06:00',
            ],
            [
                'project_name' => 'マンション#7',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',                
                'created_at' => '2015-08-16 00:07:00',
                'updated_at' => '2015-08-16 00:07:00',
            ],
            [
                'project_name' => 'マンション#8',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',                
                'created_at' => '2015-08-16 00:08:00',
                'updated_at' => '2015-08-16 00:08:00',
            ],
            [
                'project_name' => 'マンション#9',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:09:00',
                'updated_at' => '2015-08-16 00:09:00',
            ],
            [
                'project_name' => 'マンション#10',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:10:00',
                'updated_at' => '2015-08-16 00:10:00',
            ],
            [
                'project_name' => 'マンション#11',
                'user_name' => '担当三郎',
                //'user_id' => 'data2',
                'status' => 'data3',
                'm_data4' => 'data4',
                'm_data5' => 'data5',
                'm_data6' => 'data6',
                'm_data7' => 'data7',
                'm_data8' => 'data8',
                'm_data9' => 'data9',
                'user_name0' => 'data10',
                'user_name1' => 'data11',
                'user_name2' => 'data12',
                'user_name3' => 'data13',
                'user_name4' => 'data14',
                'user_name5' => 'data15',
                'user_name6' => 'data16',
                'user_name7' => 'data17',
                'user_name8' => 'data18',
                'user_name9' => 'data19',               
                'created_at' => '2015-08-16 00:11:00',
                'updated_at' => '2015-08-16 00:11:00',
            ],
        ]);
    }
}
